# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Careba' do
  pod 'YandexMapKit'
  pod 'iOS-Slide-Menu'
  pod 'libPhoneNumber-iOS', '~> 0.7'
  pod 'CountryPicker'
  pod 'ReactiveCocoa'
  pod 'BKMoneyKit'
  pod 'AFNetworking'
  pod 'Mantle'
  pod 'MBProgressHUD'
  pod 'M13BadgeView'
  pod 'UIAlertView-Blocks'
  pod 'DTInlineDatePicker'
end

